### ISSUE TITLE
Un poco largo?

### ISSUE THREAD

**Issue by lucaslencinas-zz** [mgarciaisaia/github-translations#2]
En la [guia de issues](https://github.com/mgarciaisaia/github-translations/blob/spanish/guides/features/issues.md) se hablan de algunos temas que no me parecen tan relevantes. 
Si la idea era hacer una traduccion _amena_ de la guia original no le encontré ningun error a simple vista. 
Tal vez estaria bueno, que sea menos de la mitad de contenido con lo minimo e indispensable de informacion acerca de los issues. Lo que esta a partir de **_Notificaciones, @mentions y referencias**_ para mi, si fuese un chico que cursa operativos y 5 materias mas, y estoy hasta las bolas con todo, no me sirve. 
Se podria hacer una "_2da parte_" con eso y con lo que habias hecho antes de _Pull requests_ si mal no recuerdo.
Es solo una opinion.

**Comment by mgarciaisaia** [comment]
La idea del repo, sí, es hacer traducciones de las guías publicadas por GitHub. De hecho, la organización de los archivos en el repo trata de imitar la de las URLs de GitHub (`guides/activities/hello-world.md` es la traducción de https://guides.github.com/activities/hello-world/, y así).

Eventualmente se podría hacer algún "plugin" o algo por el estilo que trate de buscar en este repo las traducciones al abrir una página de soporte en GitHub, ponele (nada, no va a pasar nunca, pero _podría_).

Para usar en @sisoputnfrba, nada, haré(mos) otros materiales, en los que sí comparto la mayoría de las observaciones que hacés :+1:
